### ISSUE TITLE
Error when loading pre-trained weights for vit_l16

### ISSUE THREAD

**Issue by soc12** [faustomorales/vit-keras#1]
Exception: URL fetch failure on https://github.com/faustomorales/vit-keras/releases/download/dl/ViT-L_16_imagenet21k+imagenet2012.npz: 404 -- Not Found

**Comment by faustomorales** [comment]
Thanks so much for raising this! Looks like there was an error uploading weights to GitHub. This is fixed as of f33a69b34af48aa8d37fc45787fbe49bc303095c (which is now v0.0.5 on PyPi).
