### ISSUE TITLE
tf.SavedModel ValueError: ('Cannot serialize', functools.partial(<function gelu at 0x15b6d55e0>, approximate=False)) 

### ISSUE THREAD

**Issue by cocoinit23** [faustomorales/vit-keras#15]
Thanks to create a nice implementation and package.
I was facing an error in saving model.

My tensorflow environment is below.
> pip freeze | grep tensor
tensorboard==2.4.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.4.0
tensorflow-addons==0.11.2
tensorflow-datasets==4.0.0
tensorflow-estimator==2.4.0
tensorflow-io==0.17.0
tensorflow-metadata==0.26.0
tensorflow-probability==0.12.1

Saving model as h5 format can be done without any problems.

>import tensorflow as tf
import vit_keras.vit as vit
model = vit.vit_b16(
    image_size=224,
    pretrained=True,
    include_top=True,
    pretrained_top=False,
)
opt = tf.keras.optimizers.Adam()
loss = tf.keras.losses.CategoricalCrossentropy()
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])
tf.saved_model.save(model,"ViT")
model.save('ViT.h5')

However, When I try to save model as SavedModel format, I got an error.

>import tensorflow as tf
import vit_keras.vit as vit
model = vit.vit_b16(
    image_size=224,
    pretrained=True,
    include_top=True,
    pretrained_top=False,
)
opt = tf.keras.optimizers.Adam()
loss = tf.keras.losses.CategoricalCrossentropy()
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])
tf.saved_model.save(model,"ViT")

>WARNING:absl:Found untraced functions such as MultiHeadDotProductAttention_1_layer_call_and_return_conditional_losses, MultiHeadDotProductAttention_1_layer_call_fn, LayerNorm_0_layer_call_and_return_conditional_losses, LayerNorm_0_layer_call_fn, LayerNorm_2_layer_call_and_return_conditional_losses while saving (showing 5 of 480). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as MultiHeadDotProductAttention_1_layer_call_and_return_conditional_losses, MultiHeadDotProductAttention_1_layer_call_fn, LayerNorm_0_layer_call_and_return_conditional_losses, LayerNorm_0_layer_call_fn, LayerNorm_2_layer_call_and_return_conditional_losses while saving (showing 5 of 480). These functions will not be directly callable after loading.
ValueError                                Traceback (most recent call last)
<ipython-input-19-c2f83d2b6f69> in <module>
----> 1 tf.saved_model.save(model,"ViT")
      2 
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in save(obj, export_dir, signatures, options)
   1030   meta_graph_def = saved_model.meta_graphs.add()
   1031 
-> 1032   _, exported_graph, object_saver, asset_info = _build_meta_graph(
   1033       obj, signatures, options, meta_graph_def)
   1034   saved_model.saved_model_schema_version = constants.SAVED_MODEL_SCHEMA_VERSION
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _build_meta_graph(obj, signatures, options, meta_graph_def)
   1196 
   1197   with save_context.save_context(options):
-> 1198     return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
   1160         function_aliases[fdef.name] = alias
   1161 
-> 1162   object_graph_proto = _serialize_object_graph(saveable_view,
   1163                                                asset_info.asset_index)
   1164   meta_graph_def.object_graph_def.CopyFrom(object_graph_proto)
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _serialize_object_graph(saveable_view, asset_file_def_index)
    752 
    753   for obj, obj_proto in zip(saveable_view.nodes, proto.nodes):
--> 754     _write_object_proto(obj, obj_proto, asset_file_def_index,
    755                         saveable_view.function_name_map)
    756   return proto
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _write_object_proto(obj, proto, asset_file_def_index, function_name_map)
    798           version=versions_pb2.VersionDef(
    799               producer=1, min_consumer=1, bad_consumers=[]),
--> 800           metadata=obj._tracking_metadata)
    801       # pylint:enable=protected-access
    802     proto.user_object.CopyFrom(registered_type_proto)
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in _tracking_metadata(self)
   3077   @property
   3078   def _tracking_metadata(self):
-> 3079     return self._trackable_saved_model_saver.tracking_metadata
   3080 
   3081   def _list_extra_dependencies_for_serialization(self, serialization_cache):
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py in tracking_metadata(self)
     53     # TODO(kathywu): check that serialized JSON can be loaded (e.g., if an
     54     # object is in the python property)
---> 55     return json_utils.Encoder().encode(self.python_properties)
     56 
     57   def list_extra_dependencies_for_serialization(self, serialization_cache):
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py in python_properties(self)
     39   def python_properties(self):
     40     # TODO(kathywu): Add python property validator
---> 41     return self._python_properties_internal()
     42 
     43   def _python_properties_internal(self):
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py in _python_properties_internal(self)
     33 
     34   def _python_properties_internal(self):
---> 35     metadata = super(ModelSavedModelSaver, self)._python_properties_internal()
     36     # Network stateful property is dependent on the child layers.
     37     metadata.pop('stateful')
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py in _python_properties_internal(self)
     57     )
     58 
---> 59     metadata.update(get_config(self.obj))
     60     if self.obj.input_spec is not None:
     61       # Layer's input_spec has already been type-checked in the property setter.
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py in get_config(obj)
    116     # When loading, the program will attempt to revive the object from config,
    117     # and if that fails, the object will be revived from the SavedModel.
--> 118     config = generic_utils.serialize_keras_object(obj)['config']
    119 
    120   if config is not None:
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    243     name = get_registered_name(instance.__class__)
    244     try:
--> 245       config = instance.get_config()
    246     except NotImplementedError as e:
    247       if _SKIP_FAILED_SERIALIZATION:
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py in get_config(self)
    469       # of `self.layers`). Note that `self._layers` is managed by the
    470       # tracking infrastructure and should not be used.
--> 471       layer_configs.append(generic_utils.serialize_keras_object(layer))
    472     config = {
    473         'name': self.name,
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    243     name = get_registered_name(instance.__class__)
    244     try:
--> 245       config = instance.get_config()
    246     except NotImplementedError as e:
    247       if _SKIP_FAILED_SERIALIZATION:
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py in get_config(self)
   1227             self.units,
   1228         'activation':
-> 1229             activations.serialize(self.activation),
   1230         'use_bias':
   1231             self.use_bias,
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/activations.py in serialize(activation)
    499       activation.__name__ in _TF_ACTIVATIONS_V2):
    500     return _TF_ACTIVATIONS_V2[activation.__name__]
--> 501   return serialize_keras_object(activation)
    502 
    503 
~/.pyenv/versions/py384/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    269   if hasattr(instance, '__name__'):
    270     return get_registered_name(instance)
--> 271   raise ValueError('Cannot serialize', instance)
    272 
    273 
ValueError: ('Cannot serialize', functools.partial(<function gelu at 0x15b6d55e0>, approximate=False))

Also, the same error occurred in ModelCheckpoint callback.
>tf.keras.callbacks.ModelCheckpoint("ViT.ckpt", verbose=1, save_best_only=True, save_weights_only=False, save_freq='epoch')

**Comment by faustomorales** [comment]
Thanks for raising this issue. This is now fixed in 1805a98633c5094a7a45f8535f91364b143f4f26  ([v0.0.14](https://pypi.org/project/vit-keras/0.0.14/))

**Comment by cocoinit23** [comment]
I updated pip package and I could save the model as SavedModel format successfully using both tf.saved_model.save and tf.keras.callbacks.ModelCheckpoint.
Thank you for quick modification !
