### ISSUE TITLE
different image size in fine-tuning

### ISSUE THREAD

**Issue by captainst** [faustomorales/vit-keras#29]
Hi there,

I saw the implementation using a convolution to generate fixed size hidden vector from a variable size of input image. That's brilliant!
However, I am wondering if the fine-tuning result would be degradated, using a different input image size, say, 224, rather than the official input size, 384, as shown in your example.

Many thanks !

**Comment by SaadTazroute** [comment]
I will wait for a response :smile:

**Comment by sutummala** [comment]
Based on my experience, I did not see any downgrade performance at 224 resolution compared with 384
