### ISSUE TITLE
Different number of channels 

### ISSUE THREAD

**Issue by minimatest** [faustomorales/vit-keras#31]
Hello, 

I have an image classification problem where each image has 10 channels: `(10,255,255)`. How do I define the model to work with such images?

**Comment by sutummala** [comment]
Treat each channel separately: I mean copy 2 more times to use the pretrained and finetuned ViT models. Then use time distributed for 10 channels.

**Comment by daniel-furman** [comment]
Anybody else figure this n-band problem out for ViT keras? Not sure what @sutummala is getting at exactly above.
