### ISSUE TITLE
error with visualization

### ISSUE THREAD

**Issue by sutummala** [faustomorales/vit-keras#32]
There seems to be an error in the visualization file at  grid_size = int(np.sqrt(model.layers[5].output_shape[0][-2] - 1)). It is hard coded and seems not suitable for 224 x 224 resolution? Any help is appreciated.

**Comment by faustomorales** [comment]
Hi there -- This sounds like a problem with the code but it is impossible to trace the issue with the information you have provided. For that reason (lack of information), I am closing this issue. If you provide a *minimal* code snippet that reproduces the problem, I am happy to re-open the issue. Please note that, the more succinct and targeted your code snippet, the more likely it is that I or another user will be able to help resolve the problem.
